apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../helm/aegis-gateway
  - ../../helm/aegis-scanner
  - ../../helm/aegis-control-plane
  - ../kubernetes/network-policy.yaml
  - ../kubernetes/kyverno-policies.yaml
